id: I7C0C9292
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:07:00+00:00'
last_modified: '2022-06-10T10:54:07.759911+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24729
  title: འབྲི་གུང་རྒྱུད་བཞིའི་དཀའ་མཆན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    20E8:
      image_group_id: I1KG24731
      title: ''
      total_pages: 995
      order: 1
      base_file: 20E8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
